---
id: "00008"
alias: Back Door - Not Home
hide_entity: true
trigger:
  - entity_id: binary_sensor.back_door_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.rb_iphone
    state: not_home
  - condition: state
    entity_id: device_tracker.je_iphone
    state: not_home
action:
  - data:
      title: Back Door
      message: Back door opened when nobody is home
    service: notify.ios_je_iphone
