---
id: "00007"
alias: HVAC on and Front Door Open Long
trigger:
  - entity_id: binary_sensor.aeon_labs_zw089_recessed_door_sensor_gen5_sensor
    platform: state
    from: "off"
    to: "on"
    for:
      minutes: 10
condition:
  condition: or
  conditions:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ states.climate.thermostat.state == 'heat'}}"
        - condition: template
          # yamllint disable-line rule:line-length
          value_template: "{{ states.weather.dark_sky.attributes.temperature | float < states.climate.thermostat.attributes.temperature | float }}"
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ states.climate.thermostat.state == 'cool'}}"
        - condition: template
          # yamllint disable-line rule:line-length
          value_template: "{{ states.weather.dark_sky.attributes.temperature | float > states.climate.thermostat.attributes.temperature | float }}"
action:
  - data:
      message: Front door open and HVAC is running
      title: HVAC Alert
    service: notify.mobile_app_john_iphone
