---
id: "00006"
alias: Front Door - Not Home
hide_entity: true
trigger:
  - entity_id: binary_sensor.aeon_labs_zw089_recessed_door_sensor_gen5_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.robert_iphone
    state: not_home
  - condition: state
    entity_id: device_tracker.john_iphone
    state: not_home
action:
  - data:
      title: Front Door
      message: Front door opened when nobody is home
    service: notify.mobile_app_john_iphone
