---
id: "00010"
alias: Garage Door - Not Home
trigger:
  - entity_id: binary_sensor.ecolink_garage_door_tilt_sensor_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.robert_iphone
    state: not_home
  - condition: state
    entity_id: device_tracker.john_iphone
    state: not_home
action:
  - data:
      title: Garage Door
      message: Garage door opened when nobody is home
    service: notify.mobile_app_john_iphone
