---
id: "00010"
alias: Garage Door - Not Home
hide_entity: true
trigger:
  - entity_id: binary_sensor.ecolink_garage_door_tilt_sensor_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.rb_iphone
    state: not_home
  - condition: state
    entity_id: device_tracker.je_iphone
    state: not_home
action:
  - data:
      title: Garage Door
      message: Garage door opened when nobody is home
    service: notify.ios_je_iphone
