---
id: "00011"
alias: HVAC on and Garage Door Open Long
hide_entity: true
trigger:
  - entity_id: binary_sensor.garage_tilt
    platform: state
    from: "off"
    to: "on"
    for:
      minutes: 10
condition:
  condition: or
  conditions:
    - condition: and
      conditions:
        - condition: state
          entity_id: climate.thermostat
          state: Heat
        - condition: template
          # yamllint disable-line rule:line-length
          value_template: "{{ states.weather.dark_sky.attributes.temperature | float < states.climate.thermostat.attributes.temperature | float }}"
    - condition: and
      conditions:
        - condition: state
          entity_id: climate.thermostat
          state: Cool
        - condition: template
          # yamllint disable-line rule:line-length
          value_template: "{{ states.weather.dark_sky.attributes.temperature | float > states.climate.thermostat.attributes.temperature | float }}"
action:
  - data:
      message: Garage door open and HVAC is running
      title: HVAC Alert
    service: notify.ios_je_iphone
