---
# Basement tilt sensor
sensor.ecolink_garage_door_tilt_sensor_power_management:
  ignored: true
  polling_intensity: 0

# Bathroom Zooz Multi-sensor
binary_sensor.bathroom_binary:
  ignored: true
  polling_intensity: 0
sensor.zooz_zse40_4_in_1_sensor_burglar:
  ignored: true
  polling_intensity: 0
sensor.zooz_zse40_4_in_1_sensor_appliance:
  ignored: true
  polling_intensity: 0
sensor.zooz_zse40_4_in_1_sensor_alarm_type:
  ignored: true
  polling_intensity: 0

# Basement Power Meter
