---
id: "00015"
alias: Metformin Remind Me Later
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: MF_TABLET_SNOOZE
action:
  - service: notify.mobile_app_robert_iphone
    data:
      message: "Ok. I will remind you later..."
