---
id: "00004"
alias: BP Med Taken
hide_entity: true
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: BP_TABLET_TAKEN
action:
  - service: notify.mobile_app_john_iphone
    data_template:
      message: >
        {{
          [
            "Good Job!",
            "Your ❤️ thanks you!",
            "Fist bump, bro! \uE00D",
            "Thanks for taking care of your blood pressure!",
            "Way to go!",
            "Thank you for taking your medicine today!"
          ] | random
        }}
  - service: input_boolean.turn_on
    entity_id: input_boolean.bp_medicine
